#ifndef DIO_CFG_H
#define DIO_CFG_H



/*
//PORT A

#define DIO_PIN0_DIR	DIO_DIR_OUTPUT
#define DIO_PIN1_DIR	DIO_DIR_OUTPUT
#define DIO_PIN2_DIR	DIO_DIR_OUTPUT
#define DIO_PIN3_DIR	DIO_DIR_OUTPUT
#define DIO_PIN4_DIR	DIO_DIR_OUTPUT
#define DIO_PIN5_DIR	DIO_DIR_OUTPUT
#define DIO_PIN6_DIR	DIO_DIR_OUTPUT
#define DIO_PIN7_DIR	DIO_DIR_OUTPUT


//PORT B

#define DIO_PIN8_DIR	DIO_DIR_OUTPUT
#define DIO_PIN9_DIR	DIO_DIR_OUTPUT
#define DIO_PIN10_DIR	DIO_DIR_OUTPUT
#define DIO_PIN11_DIR	DIO_DIR_OUTPUT
#define DIO_PIN12_DIR	DIO_DIR_OUTPUT
#define DIO_PIN13_DIR	DIO_DIR_OUTPUT
#define DIO_PIN14_DIR	DIO_DIR_OUTPUT
#define DIO_PIN15_DIR	DIO_DIR_OUTPUT

//PORT C

#define DIO_PIN16_DIR	DIO_DIR_OUTPUT
#define DIO_PIN17_DIR	DIO_DIR_OUTPUT
#define DIO_PIN18_DIR	DIO_DIR_OUTPUT
#define DIO_PIN19_DIR	DIO_DIR_OUTPUT
#define DIO_PIN20_DIR	DIO_DIR_OUTPUT
#define DIO_PIN21_DIR	DIO_DIR_OUTPUT
#define DIO_PIN22_DIR	DIO_DIR_OUTPUT
#define DIO_PIN23_DIR	DIO_DIR_OUTPUT

//PORT D

#define DIO_PIN24_DIR	DIO_DIR_OUTPUT
#define DIO_PIN25_DIR	DIO_DIR_OUTPUT
#define DIO_PIN26_DIR	DIO_DIR_OUTPUT
#define DIO_PIN27_DIR	DIO_DIR_OUTPUT
#define DIO_PIN28_DIR	DIO_DIR_OUTPUT
#define DIO_PIN29_DIR	DIO_DIR_OUTPUT
#define DIO_PIN30_DIR	DIO_DIR_OUTPUT
#define DIO_PIN31_DIR	DIO_DIR_OUTPUT
*/
#include "../../LIB/STD_TYPES.h"
typedef struct {
	u8 DIO_PinDirection;
	u8 DIO_InputStatus;
	
}DIO_strPinCfg_t;

extern const DIO_strPinCfg_t DIO_strPinCfg [32] ;

#endif  /*DIO_CFG_H*/